CREATE TABLE IF NOT EXISTS contratos (
  id VARCHAR(36) PRIMARY KEY,
  numero VARCHAR(50) UNIQUE NOT NULL,
  proposta_numero VARCHAR(50) NOT NULL,
  cliente_id VARCHAR(36) NOT NULL,
  cliente_nome VARCHAR(255) NOT NULL,
  tipo VARCHAR(50) NOT NULL DEFAULT 'conservacao',
  frequencia VARCHAR(50) NOT NULL DEFAULT 'mensal',
  valor_total_contrato DECIMAL(10,2) NOT NULL DEFAULT 0,
  forma_pagamento VARCHAR(50) NOT NULL DEFAULT 'mensal',
  prazo_contrato INT NOT NULL DEFAULT 12,
  garantia INT NOT NULL DEFAULT 90,
  observacoes TEXT,
  status VARCHAR(50) NOT NULL DEFAULT 'ativo',
  data_inicio DATE,
  data_fim DATE,
  data_assinatura DATE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_numero (numero),
  INDEX idx_proposta_numero (proposta_numero),
  INDEX idx_cliente_id (cliente_id),
  INDEX idx_status (status)
);
